### ISSUE TITLE
Idee di Gameplay

### ISSUE THREAD

**Issue by TheMaster0017** [rattlesmake/centurion#25]
1) Creare dinamicità grafica, in modo tale da dare un'impressione di avanzamento del mondo di gioco, come ad esempio la miglioria estetica (che può essere fatta attraverso un cambio della classe di tutte le strutture coinvolte) di edifici a seguito della scoperta di una tecnologia (ad esempio il cambio grafico in seguito al rinforzo di porte e muraglia);
2) Creare diversità negli insediamenti. A questo proposito, a seconda che la mappa sia grande, media o o piccola, le fortificazioni dei giocatori avranno una dimensione corrispondente alla grandezza della mappa: tale dimensione influisce essenzialmente sulla strutturazione e sulla complessità dell'insediamento. Ad esempio, una città di grandi dimensioni, avrà una doppia cinta muraria e delle abitazioni extra, mentre una piccola sarà sulla falsariga di quelle di Imperivm; sarà inoltre possibile trovare degli insediamenti neutrali di grandezza inferiore a quella dei giocatori (mappa grande => giocatori con insediamenti grandi => fortezze neutrali medie e piccole);
3)  Creare il ciclo giorno/notte. Mentre il giorno non comporta alcuna penalità, la notte abbassa il campo visivo di tutte le unità lontane da un insediamento, per creare l'effetto oscurità. L'ideale, per ricreare l'effetto desiderato, sarebbe quello di spawnare dei game object "Torch", che compariranno automaticamente, ed in punti stabiliti nell'entity di ogni edificio, e che durante il giorno avranno l'attributo "Invisibile" attivo. Il ciclo giorno/notte può essere attivato o disattivato dal menù delle opzioni della partita (Per evitare discordanze tra giocatori nel multiplayer con impostazioni differenti).
4) Ogni città ha uno spazio più o meno esteso nel quale verranno generate delle abitazioni aggiuntive quando viene scoperta la tecnologia "Costruisci alloggi". Tali abitazioni forniranno un incremento della popolazione massima oltre che un upgrade grafico.
5) Ogni insediamento nella mappa, quale sia esso guidato dal giocatore o dall'intelligenza artificiale, possiede un nome proprio che verrà estratto da una lista corrispondente. Tutti questi elenchi dovranno contenere un quantitativo di nomi che sia superiore al numero massimo di insediamenti generabili in una mappa grande, e questo per evitare che in caso venga scelta una sola fazione, il numero di nomi a disposizione si esaurisce e due o più insediamenti avranno lo stesso.

**Comment by azureon7** [comment]
https://github.com/rattlesmake/centurion/wiki/Idee
