### ISSUE TITLE
[BUG] MovingObject e AnyWindowsOpened

### ISSUE THREAD

**Issue by TheMaster0017** [rattlesmake/centurion#49]
Nel caso in cui un edificio è selezionato e si dovesse aprire una qualunque finestra, ad esempio quella di Object Properties, se si tiene premuto il tasto sinistro del mouse sul tasto chiudi, il gioco chiuderà la finestra, ma sarà convinto che si vuole compiere l'azione di spostamento dell'edificio selezionato. Impedire quindi che le due azioni avvengano simultaneamente.

**Comment by azureon7** [comment]
Solved
