### ISSUE TITLE
Selection box, eccezione non gestita

### ISSUE THREAD

**Issue by TheMaster0017** [rattlesmake/centurion#74]
Cliccando col tasto sinistro su una selection box che è stata implementata soltanto a livello grafico e non a livello contenutistico, ossia l'elenco di ciò che deve mostrare, e quindi mancante della condition script nel file .xml, il gioco crasha restituendo un errore irreversibile.

**Comment by azureon7** [comment]
Ok, c'è da renderizzare solo il rettangolo senza placeholder né opzioni in tal caso. Provvedo a fixare il problema
